version: "3.7"

services:
  sdb_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - sdb_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend

  sdb_science_db_graphql_server:
    depends_on:
      - sdb_postgres
    build:
      context: ./graphql-server
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - .:/usr/ScienceDbStarterPack
      # Use the Sequelize config adjusted for the Docker setup of ScienceDbStarterPack:
      - ./graphql-server/config/config_postgres_docker.json:/usr/ScienceDbStarterPack/graphql-server/config/config.json
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ./migrateDbAndStartServer.sh
    labels:
      traefik.enable: "true"
      traefik.backend: "sdb_science_db_graphql_server"
      #traefik.frontend.rule: "Host:v-10292.cloud.intertech.de,vmd17974.contabo.host;PathPrefix:/api"
      traefik.frontend.rule: "Host:api.reconstructdb.org"
      #traefik.frontend.auth.basic: 'testuser:$$apr1$$QBCuO60R$$pJIFSe2x8L/cTbOBOvoOt1'
      #traefik.frontend.headers.SSLRedirect=true
      traefik.docker.network: "reverseproxy"
      traefik.port: "3000"
    restart: unless-stopped
    networks:
      - backend
      - reverseproxy

  sdb_science_db_app_server:
    depends_on:
      - sdb_postgres
      - sdb_science_db_graphql_server
    build:
      context: ./single-page-app
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - VUE_APP_SERVER_URL=http:///api.reconstructdb.org/graphql
      - VUE_APP_LOGIN_URL=http://api.reconstructdb.org/login
      - VUE_APP_MAX_UPLOAD_SIZE=500
    volumes:
      - .:/usr/ScienceDbStarterPack
    # Install dependencies and start single-page-app-server in development
    # mode.
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run serve
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.backend: "sdb_science_db_app_server"
      #traefik.frontend.rule: "Host:v-10292.cloud.intertech.de,vmd17974.contabo.host;PathPrefix:/api"
      traefik.frontend.rule: "Host:spa.reconstructdb.org"
      #traefik.frontend.auth.basic: 'testuser:$$apr1$$QBCuO60R$$pJIFSe2x8L/cTbOBOvoOt1'
      #traefik.frontend.headers.SSLRedirect=true
      traefik.docker.network: "reverseproxy"
      traefik.port: "8080"
    networks:
      - backend
      - reverseproxy

#  sdb_minio:
#    image: minio/minio:RELEASE.2019-02-20T22-44-29Z
#    volumes:
#      - sdb_minio_data:/data
#    ports:
#      - "9000:9000"
#    environment:
#      MINIO_ACCESS_KEY: sciencedb
#      MINIO_SECRET_KEY: sciencedb
#    command: server /data
#    restart: unless-stopped
#    networks:
#      - backend
#      - reverseproxy

volumes:
  sdb_db_data:
  sdb_minio_data:
networks:
  reverseproxy:
    external: true
  backend:
