version: "3.2"

services:
  bp_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - bp_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bp_science_db_graphql_server:
    depends_on:
      - bp_postgres
    build:
      context: ./graphql-server
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command:
      - ./migrateDbAndStartServer.sh

  bp_science_db_app_server:
    depends_on:
      - bp_postgres
      - bp_science_db_graphql_server
    build:
      context: ./single-page-app
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    command: npm run dev

  bp_minio:
    image: minio/minio:RELEASE.2019-02-20T22-44-29Z
    volumes:
      - bp_minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

volumes:
  bp_db_data:
  bp_minio_data:
